### ISSUE TITLE
ZEIR Rapid Pro bug: Handle child contacts whose nurse information is incorrect

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-server-core#576]
These child contacts are ignored since the nurse's information is incorrect by not having the correct facility or location

## Tasks

- [ ] Add a flow to confirm that the provider information tallies with OpenSRP locations and facilities
- [ ] Fix the data on RapidPro for nurses/providers with incorrect information
- [ ] Reset the OpenSRP connector to reprocess all missed data
